# SOPS configuration for dotfiles secrets
# Public key: age1awwwkumrc778dt5s3lczds88lkgjpz4cvs7m6pusd00lgr6lldtsr287ea

creation_rules:
  - path_regex: secrets/.*\.(yaml|json|env|ini)$
    age: age1awwwkumrc778dt5s3lczds88lkgjpz4cvs7m6pusd00lgr6lldtsr287ea

  - path_regex: .*\.enc\.(yaml|json|env|ini)$
    age: age1awwwkumrc778dt5s3lczds88lkgjpz4cvs7m6pusd00lgr6lldtsr287ea
