# SOPS configuration for dotfiles secrets
# Public key: age10vz5uuhpm7h9fcc5kpsy23wvjmk7m3sscwx7m79gj54yxy5m0fmq8ru3qc

creation_rules:
  - path_regex: secrets/.*\.(yaml|json|env|ini)$
    age: age10vz5uuhpm7h9fcc5kpsy23wvjmk7m3sscwx7m79gj54yxy5m0fmq8ru3qc

  - path_regex: .*\.enc\.(yaml|json|env|ini)$
    age: age10vz5uuhpm7h9fcc5kpsy23wvjmk7m3sscwx7m79gj54yxy5m0fmq8ru3qc
