# Setup homebrew & mise for non-interactive, login shells
# Examples: ssh user@host 'command', zsh -l -c 'command'
if [[ ! -o interactive ]] && [[ -o login ]]; then
    eval "$(/opt/homebrew/bin/brew shellenv)"
    eval "$(mise activate zsh --shims)"
fi
